spring:
  application:
    name: video-metadata-service
  
  # Database Configuration (H2 for Docker demo)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis Configuration for Docker
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForVideoMetadataService2025}
    expiration: 86400000 # 24 hours in milliseconds
  
  # Cache Configuration
  cache:
    video-stats-ttl: 600 # 10 minutes in seconds
    job-stats-ttl: 300 # 5 minutes in seconds
    video-cache-ttl: 3600 # 1 hour in seconds
    job-cache-ttl: 900 # 15 minutes in seconds
  
  # User Management
  users:
    - id: 1
      username: "admin"
      password: "$2a$10$MrfNWRpGG9p19.HQoHajIudQwGTJoTaduC490JyDUNhpYmHgW0/Iy" # admin123
      roles: ["ADMIN", "USER"]
    - id: 2
      username: "user"
      password: "$2a$10$sHF5qA5nCdMALlcZi174oubXVeNOc8qJRT1q/3uzs7cNukfypVy8i" # user123
      roles: ["USER"]
  
  # External API Configuration
  external-apis:
    mock:
      base-url: "https://dummyjson.com"
      enabled: true
      timeout: 2000
  
  # Import Configuration
  import:
    batch-size: 100
    max-retries: 3
    retry-delay: 1000

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    com.goldmediatech.videometadata: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: Video Metadata Service API (Docker)
    description: Backend service for managing and analyzing video metadata from multiple platforms
    version: 1.0.0
    contact:
      name: GoldmediaTech
      email: support@goldmediatech.com 